name:                levnor
version:             0.1.0.0
github:              "timecatler/levnor"
license:             BSD3
author:              "Tim Catler"
maintainer:          "timecatler@gmail.com"
copyright:           "GNU GPLv3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/timecatler/levnor#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- statistics
- flow

library:
  source-dirs: src

executables:
  levnor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - levnor

tests:
  levnor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - levnor
